/**
 * The poster catalogue.
 *
 * These are the stills that head the site's major sections. They lived in
 * `three/registry.ts` while a WebGL layer was planned, where each one was the
 * fallback for a 3D scene of the same name; the 3D layer has since been removed
 * and the posters are simply the images now. The ids read like scene names
 * because that is what the sections are still called in the specs and in the
 * routes — renaming them would churn every call site to say the same thing.
 *
 * ## They are placeholders, and that is visible
 *
 * Eight of the nine are solid-tone AVIFs a few hundred bytes each, generated by
 * `scripts/make-placeholder-posters.ts`. `journey` is the exception and is real
 * artwork. Spec P2 forbids substituting stock photography, so these hold the
 * layout honestly until the studio's own photography exists rather than
 * borrowing someone else's.
 *
 * ## The alt text is a claim, not a description
 *
 * Each `alt` states what the section argues, because that is what a screen
 * reader user needs from it — not an inventory of pixels. Where the image is
 * atmospheric rather than depictive (`journey`), the alt describes the artwork
 * and the surrounding page carries the substance.
 */

export const POSTER_IDS = [
  'hero',
  'persona-router',
  'vastu',
  'space-score',
  'space-os',
  'portfolio',
  'journey',
  'pricing-axis',
  'nri-globe',
] as const;

export type PosterId = (typeof POSTER_IDS)[number];

export type Poster = {
  src: string;
  /** The CLAIM the section makes — not a description of pixels. Read aloud by
   *  screen readers, so it must carry the same argument the section does. */
  alt: string;
  aspect: `${number}/${number}`;
  /** True for 'hero' only — this is the LCP element. */
  priority?: boolean;
};

/** Total record: every id must have a poster or the build fails typecheck. */
export const POSTERS: Record<PosterId, Poster> = {
  hero: {
    src: '/posters/hero.avif',
    alt: 'A finished living room resolved along a line of gold light: pendant lit, sofa placed, plant settled — space and applied intelligence producing a designed home.',
    aspect: '16/9',
    priority: true,
  },
  'persona-router': {
    src: '/posters/persona-router.avif',
    alt: 'Six lit routes into the studio, one for each kind of visitor, arranged around a Chennai skyline marker.',
    aspect: '16/9',
  },
  vastu: {
    src: '/posters/vastu.avif',
    alt: 'A floor plan under a gold Vastu grid: favourable zones marked in gold, zones needing review in teal, with a chip confirming a human designer reviewed the result.',
    aspect: '4/3',
  },
  'space-score': {
    src: '/posters/space-score.avif',
    alt: 'A four-arc gauge rating a room on wellness, function, aesthetics and sustainability, each arc filled to its measured value.',
    aspect: '1/1',
  },
  'space-os': {
    src: '/posters/space-os.avif',
    alt: 'The client portal on a tablet, showing a moodboard, live build progress and a visible budget — the project as the client sees it.',
    aspect: '4/3',
  },
  portfolio: {
    src: '/posters/portfolio.avif',
    alt: 'Completed Chennai projects presented as material-rich panels along the gold axis.',
    aspect: '16/9',
  },
  journey: {
    src: '/posters/journey.avif',
    // The ONLY poster that is real artwork rather than a solid-tone
    // placeholder: the studio's own "Luxurious Section Divider". It draws the
    // Axis motif directly, which is why it fits this slot and no other — the
    // composition is portrait, and the journey section descends the axis.
    //
    // The alt describes what this IMAGE shows, not what a scene might have.
    // /process lists all seven stages as real text directly beneath it, so
    // nothing is lost by the picture being atmospheric.
    alt: 'Fine gold lines crossing a deep field and meeting at lit points — the Axis the studio draws its work along.',
    aspect: '9/16',
  },
  'pricing-axis': {
    src: '/posters/pricing-axis.avif',
    alt: 'A gold bead resting on the axis at a published fee, illustrating pricing that is stated openly rather than quoted privately.',
    aspect: '16/9',
  },
  'nri-globe': {
    src: '/posters/nri-globe.avif',
    alt: 'An arc drawn from the diaspora to Chennai, tracing how a home here is designed and delivered from abroad.',
    aspect: '1/1',
  },
};
