/**
 * The 3D palette — the single source of colour for everything under `three/`.
 *
 * ## Why this file exists rather than reading the CSS custom properties
 *
 * The DOM gets its colour from `styles/tokens.css`, generated by
 * `scripts/build-tokens.ts` out of `tokens/luxe-axis.tokens.json`. WebGL cannot
 * use those: a `meshStandardMaterial` needs a `THREE.Color`, not a
 * `var(--color-accent)`, and resolving custom properties per-frame via
 * `getComputedStyle` is a forced style recalculation on the main thread — the
 * exact thing a 60fps budget cannot afford.
 *
 * So the values are mirrored here by hand, and `tests/unit/palette.test.ts`
 * asserts they still match the token file. That test is the guard: it is what
 * turns "someone changed the brand and forgot the 3D layer" from a silent
 * visual drift into a failing build.
 *
 * That drift is not hypothetical. At the time this file was written,
 * `GenericScene` and `VastuScene` were still painting `#C9A84C` and `#1A7A85`
 * — the gold and teal from *before* the emerald rebrand — because nothing
 * connected them to the tokens. Both are wrong on screen today.
 *
 * ## sRGB in, linear out — handled for us
 *
 * three r152+ ships `ColorManagement.enabled = true` by default, and R3F sets
 * the renderer's output colour space to sRGB. A hex string assigned to a
 * material is therefore interpreted as sRGB and converted to linear working
 * space automatically. These constants are plain sRGB hex, identical to the
 * token file, and must NOT be pre-converted — doing that by hand double-applies
 * the transform and washes every material out.
 */

/** Brand primitives. Mirrors `color.brand` in tokens/luxe-axis.tokens.json. */
export const PALETTE = {
  /** Primary Deep Emerald — the ground plane and far walls. */
  emerald: '#1E3F2E',
  /** Deepest Emerald void — the fog colour and the canvas clear. */
  emeraldVoid: '#12291E',
  /** Elevated dark glass — upholstery, cabinet carcasses. */
  emeraldRaised: '#28523D',
  /** Elevated-2 — hover and rim-lit edges on dark surfaces. */
  emeraldHi: '#33634B',

  /** Accent Luxe Gold — the Axis itself, and every metal fitting. */
  gold: '#FFC107',
  /** Deep gold — unlit sides of gold objects, where champagne would blow out. */
  goldDeep: '#B8860B',
  /** Champagne — the specular highlight stop on all metal. */
  goldChampagne: '#FFE082',

  /** Vastu-Tech signal — zone markers, data overlays. */
  teal: '#1E6B52',
  /** Tech Sapphire — bright signal accent, readable against emerald. */
  tealBright: '#38BDF8',

  /** Warm Clay — light surfaces, plaster, upholstery highlights. */
  clay: '#E9E3D8',
  /** Raised clay — the lightest surface in the system. */
  clayHi: '#F5F1E8',
  /** Sunken clay — inset panels, shadowed light surfaces. */
  claySunken: '#DDD5C6',
} as const;

export type PaletteKey = keyof typeof PALETTE;

/**
 * Scene-wide atmospheric settings.
 *
 * `fogNear`/`fogFar` are in world units and assume the room scenes' shared
 * scale of roughly 1 unit = 1 metre (see `three/rooms/RoomShell.tsx`). Fog is
 * doing real work here beyond mood: it is what lets a room scene cull its far
 * wall without the cut being visible, and it hides the seam where a low-poly
 * LOD swaps in.
 */
export const ATMOSPHERE = {
  fogColor: PALETTE.emeraldVoid,
  fogNear: 6,
  fogFar: 26,
  /** Canvas clear colour. Matches `--color-surface-deep` so the WebGL layer and
   *  the DOM behind it are the same black, and a scene fading out has nothing
   *  to fade *to* except the page itself. */
  clear: PALETTE.emeraldVoid,
} as const;
