import type { ComponentType } from 'react';

export const SCENE_IDS = [
  'hero', 'persona-router', 'vastu', 'space-score',
  'space-os', 'portfolio', 'journey', 'pricing-axis', 'nri-globe',
] as const;

export type SceneId = (typeof SCENE_IDS)[number];

export type ScenePoster = {
  src: string;
  /** The CLAIM the scene makes — not a description of pixels. Read aloud by
   *  screen readers in place of the scene, so it must carry the same argument. */
  alt: string;
  aspect: `${number}/${number}`;
  /** True for 'hero' only — this is the LCP element. */
  priority?: boolean;
};

export type SceneModule = {
  Scene: ComponentType<{ sceneId: SceneId }>;
  budgetKB: number;
  minTier: 'T2' | 'T3';
  flag: string;
};

/**
 * Total record: every scene must have a poster or the build fails typecheck.
 *
 * Eight of the nine are still the solid-navy placeholders generated by
 * `scripts/make-placeholder-posters.ts` — workstream B-01's art-directed stills
 * do not exist yet, and the hero and portfolio slots in particular need real
 * photography rather than artwork (Spec P2 forbids stock substitution).
 * `journey` is the exception; see its entry.
 */
export const POSTERS: Record<SceneId, ScenePoster> = {
  hero: {
    src: '/posters/hero.avif',
    alt: 'A finished living room resolved along a line of gold light: pendant lit, sofa placed, plant settled — space and applied intelligence producing a designed home.',
    aspect: '16/9',
    priority: true,
  },
  'persona-router': {
    src: '/posters/persona-router.avif',
    alt: 'Six lit routes into the studio, one for each kind of visitor, arranged around a Chennai skyline marker.',
    aspect: '16/9',
  },
  vastu: {
    src: '/posters/vastu.avif',
    alt: 'A floor plan under a gold Vastu grid: favourable zones marked in gold, zones needing review in teal, with a chip confirming a human designer reviewed the result.',
    aspect: '4/3',
  },
  'space-score': {
    src: '/posters/space-score.avif',
    alt: 'A four-arc gauge rating a room on wellness, function, aesthetics and sustainability, each arc filled to its measured value.',
    aspect: '1/1',
  },
  'space-os': {
    src: '/posters/space-os.avif',
    alt: 'The client portal on a tablet, showing a moodboard, live build progress and a visible budget — the project as the client sees it.',
    aspect: '4/3',
  },
  portfolio: {
    src: '/posters/portfolio.avif',
    alt: 'Completed Chennai projects presented as material-rich panels along the gold axis.',
    aspect: '16/9',
  },
  journey: {
    src: '/posters/journey.avif',
    // The ONLY poster that is real artwork rather than a solid-navy
    // placeholder: the studio's own "Luxurious Section Divider", exported from
    // Canva. It is on-palette (navy field, gold line work, a teal accent) and
    // it draws the Axis motif directly, which is why it fits this slot and no
    // other — the composition is portrait, and the journey scene is described
    // as nodes descending the axis.
    //
    // The alt text describes what this IMAGE shows, not what the eventual 3D
    // scene will. The old text named "the seven stages … from first discovery
    // through handover and concierge care", which this artwork does not depict
    // — a screen-reader user would have been told about content that is not
    // there. /process lists all seven stages as real text directly beneath it,
    // so nothing is lost by the picture being atmospheric.
    alt: 'Fine gold lines crossing a deep navy field and meeting at lit points — the Axis the studio draws its work along.',
    aspect: '9/16',
  },
  'pricing-axis': {
    src: '/posters/pricing-axis.avif',
    alt: 'A gold bead resting on the axis at a published fee, illustrating pricing that is stated openly rather than quoted privately.',
    aspect: '16/9',
  },
  'nri-globe': {
    src: '/posters/nri-globe.avif',
    alt: 'An arc drawn from the Tamil diaspora to Chennai, tracing how a home here is designed and delivered from abroad.',
    aspect: '1/1',
  },
};

/** Registered live 3D scenes loaded dynamically per scene ID. */
export const SCENES: Partial<Record<SceneId, () => Promise<SceneModule>>> = {
  hero: () => import('./scenes/HeroScene').then((m) => m.default),
  vastu: () => import('./scenes/VastuScene').then((m) => m.default),
  'space-os': () => import('./scenes/SpaceOSScene').then((m) => m.default),
  'nri-globe': () => import('./scenes/NRIGlobeScene').then((m) => m.default),
  'persona-router': () => import('./scenes/GenericScene').then((m) => m.default),
  'space-score': () => import('./scenes/GenericScene').then((m) => m.default),
  portfolio: () => import('./scenes/GenericScene').then((m) => m.default),
  journey: () => import('./scenes/GenericScene').then((m) => m.default),
  'pricing-axis': () => import('./scenes/GenericScene').then((m) => m.default),
};
